#!/usr/bin/env python3
"""Generate an aic_engine config that replicates a specific training episode.

Reads the recorded scene (home offset, board sc_port_0 translation) from
/tmp/sc_batch_150/summary_clean.tsv and the first-frame joint positions from
the matching parquet, then writes a YAML the engine can load to put the robot
+ board in the exact pose used during that training episode.

Usage:
  pixi run python aic_utils/lerobot_robot_aic/replicate_episode.py <ep_num> \
      [--summary /tmp/sc_batch_150/summary_clean.tsv] \
      [--out /tmp/sc_eval_ep<ep>.yaml]

After writing, prints the launch command to start an eval with that config.
"""

from __future__ import annotations

import argparse
import csv
import glob
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

LEROBOT_CACHE = Path.home() / ".cache" / "huggingface" / "lerobot"

# obs.state column indices for the 7 joint_positions (slim drops these so we
# read from the non-slim merged dataset OR the source episode parquet).
JOINT_OBS_RANGE = (19, 26)  # exclusive end

# /joint_states publishes joints in alphabetical order:
#   0 = elbow_joint
#   1 = finger_joint   (gripper, ignore for arm home)
#   2 = shoulder_lift_joint
#   3 = shoulder_pan_joint
#   4 = wrist_1_joint
#   5 = wrist_2_joint
#   6 = wrist_3_joint
ARM_JOINT_INDEX_IN_FIELD = {
    "elbow_joint": 0,
    "shoulder_lift_joint": 2,
    "shoulder_pan_joint": 3,
    "wrist_1_joint": 4,
    "wrist_2_joint": 5,
    "wrist_3_joint": 6,
}


def find_row(summary_path: Path, ep_num: int) -> dict[str, str]:
    with open(summary_path) as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader)
        for row in reader:
            if not row:
                continue
            try:
                if int(row[0]) == ep_num:
                    return dict(zip(header, row))
            except ValueError:
                continue
    raise SystemExit(f"Episode {ep_num} not found in {summary_path}")


def read_first_frame_joints(repo: str) -> tuple[dict[str, float], np.ndarray]:
    parqs = sorted(glob.glob(str(LEROBOT_CACHE / repo / "data/chunk-*/*.parquet")))
    if not parqs:
        raise SystemExit(
            f"No parquet for repo {repo}. The source dataset may have been merged "
            f"into a *_merged_trimmed and the original deleted."
        )
    df = pd.concat([pd.read_parquet(p) for p in parqs])
    s_row = np.stack(df["observation.state"].values)[0]
    start, end = JOINT_OBS_RANGE
    joints_7 = s_row[start:end]
    arm = {
        name: float(joints_7[idx])
        for name, idx in ARM_JOINT_INDEX_IN_FIELD.items()
    }
    return arm, s_row


def build_yaml(ep_num: int, board_tx: float, joints: dict[str, float]) -> str:
    return f"""# Auto-generated eval config replicating training episode {ep_num}.
# Generated by aic_utils/lerobot_robot_aic/replicate_episode.py.
# Inputs: /tmp/sc_batch_150/summary_clean.tsv (scene) + parquet first frame
# (joint home). Use with `ros2 launch aic_bringup aic_gz_bringup.launch.py
# start_aic_engine:=true aic_engine_config_file:=<this file>`.

scoring:
  topics:
    - topic:
        name: "/joint_states"
        type: "sensor_msgs/msg/JointState"
    - topic:
        name: "/tf"
        type: "tf2_msgs/msg/TFMessage"
    - topic:
        name: "/tf_static"
        type: "tf2_msgs/msg/TFMessage"
        latched: true
    - topic:
        name: "/scoring/tf"
        type: "tf2_msgs/msg/TFMessage"
    - topic:
        name: "/aic/gazebo/contacts/off_limit"
        type: "ros_gz_interfaces/msg/Contacts"
    - topic:
        name: "/fts_broadcaster/wrench"
        type: "geometry_msgs/msg/WrenchStamped"
    - topic:
        name: "/aic_controller/joint_commands"
        type: "aic_control_interfaces/msg/JointMotionUpdate"
    - topic:
        name: "/aic_controller/pose_commands"
        type: "aic_control_interfaces/msg/MotionUpdate"
    - topic:
        name: "/scoring/insertion_event"
        type: "std_msgs/msg/String"
    - topic:
        name: "/aic_controller/controller_state"
        type: "aic_control_interfaces/msg/ControllerState"

task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425

trials:
  trial_1:
    scene:
      task_board:
        # task_board pose from training defaults (spawn_task_board.launch.py).
        pose:
          x: 0.25
          y: 0.0
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0
        nic_rail_0:
          entity_present: False
        nic_rail_1:
          entity_present: False
        nic_rail_2:
          entity_present: False
        nic_rail_3:
          entity_present: False
        nic_rail_4:
          entity_present: False
        sc_rail_0:
          entity_present: True
          entity_name: "sc_mount_0"
          entity_pose:
            translation: {board_tx:.6f}  # from summary_clean.tsv board_translation
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
        lc_mount_rail_0:
          entity_present: False
        sfp_mount_rail_0:
          entity_present: False
        sc_mount_rail_0:
          entity_present: False
        lc_mount_rail_1:
          entity_present: False
        sfp_mount_rail_1:
          entity_present: False
        sc_mount_rail_1:
          entity_present: False
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0
              y: 0.015385
              z: 0.04045
            roll: 0.4432
            pitch: -0.4838
            yaw: 1.3303
          attach_cable_to_gripper: True
          cable_type: "sfp_sc_cable_reversed"
    tasks:
      task_1:
        cable_type: "sfp_sc"
        cable_name: "cable_0"
        plug_type: "sc"
        plug_name: "sc_tip"
        port_type: "sc"
        port_name: "sc_port_base"
        target_module_name: "sc_port_0"
        time_limit: 180

robot:
  # Joint home values taken from the recorded episode's first-frame
  # observation.state[19..25]. The engine teleports the joints to these
  # exact values via /scoring/reset_joints, reproducing the gripper pose
  # the robot reached at episode start (after launch_randomized_episode's
  # Cartesian impedance home).
  home_joint_positions:
    shoulder_pan_joint: {joints["shoulder_pan_joint"]:.6f}
    shoulder_lift_joint: {joints["shoulder_lift_joint"]:.6f}
    elbow_joint: {joints["elbow_joint"]:.6f}
    wrist_1_joint: {joints["wrist_1_joint"]:.6f}
    wrist_2_joint: {joints["wrist_2_joint"]:.6f}
    wrist_3_joint: {joints["wrist_3_joint"]:.6f}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ep_num", type=int, help="episode number from summary_clean.tsv")
    ap.add_argument(
        "--summary", default="/tmp/sc_batch_150/summary_clean.tsv",
        help="per-episode TSV with home/board info",
    )
    ap.add_argument(
        "--out", default=None,
        help="output YAML path (default /tmp/sc_eval_ep<NNN>.yaml)",
    )
    args = ap.parse_args()

    summary = Path(args.summary)
    if not summary.exists():
        raise SystemExit(f"Summary not found: {summary}")

    row = find_row(summary, args.ep_num)
    outcome = row["outcome"]
    repo = row["repo_id"]
    if outcome != "OK":
        print(
            f"warning: episode {args.ep_num} outcome was {outcome!r}, not OK",
            file=sys.stderr,
        )

    try:
        board_tx = float(row["board_translation"])
    except ValueError:
        raise SystemExit(
            f"board_translation field is {row['board_translation']!r} — expected a float"
        )

    arm_joints, full_first = read_first_frame_joints(repo)

    out_path = Path(args.out) if args.out else Path(
        f"/tmp/sc_eval_ep{args.ep_num:03d}.yaml"
    )
    out_path.write_text(build_yaml(args.ep_num, board_tx, arm_joints))

    print(f"Wrote {out_path}")
    print()
    print(f"Episode {args.ep_num} replication info:")
    print(f"  repo:              {repo}")
    print(f"  outcome:           {outcome}")
    print(f"  TCP home (record): ({row['tcp_home_x']}, {row['tcp_home_y']}, {row['tcp_home_z']})")
    print(f"  Home offset (dxyz): ({row['home_dx']}, {row['home_dy']}, {row['home_dz']})")
    print(f"  Board sc_port_0 translation: {board_tx:+.4f} m")
    print(f"  TCP from obs.state[0..2] (first frame):"
          f" ({full_first[0]:+.4f}, {full_first[1]:+.4f}, {full_first[2]:+.4f})")
    print(f"  Arm joint home (from first-frame observation):")
    for n in ("shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint",
              "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"):
        print(f"    {n:25s}: {arm_joints[n]:+.6f}")
    print()
    print("Launch eval with this config:")
    print()
    print("  docker exec -it -u fuheng aic_eval bash -lc '")
    print("    source /ws_aic/install/setup.bash && \\")
    print("    source $HOME/ws_aic/install/setup.bash && \\")
    print("    export RMW_IMPLEMENTATION=rmw_zenoh_cpp && \\")
    print("    ros2 run rmw_zenoh_cpp rmw_zenohd & sleep 2 && \\")
    print("    ros2 launch aic_bringup aic_gz_bringup.launch.py \\")
    print("      start_aic_engine:=true \\")
    print("      ground_truth:=false \\")
    print(f"      aic_engine_config_file:={out_path}")
    print("  '")


if __name__ == "__main__":
    main()
